### ISSUE TITLE
Heap Visualizer Intermittently Prints an Error (But Works Anyway)

### ISSUE THREAD

**Issue by stamourv** [racket/plai#16]
Occasionally (maybe half the time) I run a mutator program to look at the heap visualizer, I get this error message:

```
../src/racket-releases/Racket v8.2/collects/racket/contract/private/blame.rkt:346:0: draw-rectangle: contract violation
  expected: (and/c real? (not/c negative?))
  given: -2
  in: the 3rd argument of
      (->m
       real?
       real?
       (and/c real? (not/c negative?))
       (and/c real? (not/c negative?))
       void?)
  contract from: (class bitmap-dc%)
  blaming: <pkgs>/plai-lib/gc2/private/gc-gui.rkt
   (assuming the contract is correct)
```

But the heap visualizer (and the mutator) appear to work without issue otherwise.

This has been happening since last Spring (maybe in the Fall too, I forget), but it's a relatively recent thing. Some of my students have also observed it.

**Comment by rfindler** [comment]
Judging from the content of the error message, it looks like [this line](https://github.com/racket/plai/blob/master/plai-lib/gc2/private/gc-gui.rkt#L183) is what's computing the -2 and probably because `fill-in-min-sizes` isn't getting called before `on-paint`? I'm not sure.
